"""Markdown report writer."""

from __future__ import annotations

from pathlib import Path

from endpoint_finder.discovery import api as apimod
from endpoint_finder.models import ScanResult


def _escape(value: str) -> str:
    """Escape pipe characters so table cells do not break."""
    return value.replace("|", "\\|")


def build(result: ScanResult) -> str:
    """Render the scan result as Markdown.

    Args:
        result: Completed scan result.

    Returns:
        The Markdown document as a string.
    """
    summary = apimod.summarize(result.endpoints)
    lines: list[str] = [
        f"# Endpoint report — {result.page_title or result.target}",
        "",
        f"- **Target:** <{result.target}>",
        f"- **Scanned:** {result.scan_time.strftime('%Y-%m-%d %H:%M:%S UTC')}"
        f" in {result.stats.duration_seconds}s",
        f"- **Pages crawled:** {result.stats.pages} · "
        f"**Scripts analysed:** {result.stats.scripts} · "
        f"**Network requests:** {result.stats.requests} · "
        f"**Source maps:** {result.stats.sourcemaps}",
        f"- **Endpoints:** {summary['total']} across {summary['hosts']} host(s), "
        f"{summary['routes']} distinct route(s), {summary['high_confidence']} high confidence",
        "",
    ]

    if result.technologies:
        lines += [
            "## Detected technologies",
            "",
            ", ".join(f"`{t}`" for t in result.technologies),
            "",
        ]

    counts = result.type_counts()
    if counts:
        lines += ["## Breakdown by type", "", "| Type | Count |", "| --- | ---: |"]
        lines += [f"| {name} | {count} |" for name, count in counts.items()]
        lines.append("")

    lines += ["## Endpoints", ""]
    for etype, endpoints in sorted(
        result.by_type().items(), key=lambda kv: (-len(kv[1]), kv[0].value)
    ):
        lines += [
            f"### {etype.value} ({len(endpoints)})",
            "",
            "| Method | URL | Source | Conf. |",
            "| --- | --- | --- | --- |",
        ]
        for endpoint in endpoints:
            lines.append(
                f"| `{endpoint.method.value}` | `{_escape(endpoint.url)}` | "
                f"{endpoint.source.value} | {endpoint.confidence.value} |"
            )
        lines.append("")

    if result.routes:
        lines += [
            f"## Client side routes ({len(result.routes)})",
            "",
            "_Navigable views of the single page application, not request targets._",
            "",
            *[f"- `{_escape(route)}`" for route in result.routes],
            "",
        ]

    if result.errors:
        lines += [
            "## Warnings and errors",
            "",
            "| Category | URL | Detail |",
            "| --- | --- | --- |",
        ]
        for error in result.errors[:100]:
            lines.append(
                f"| {error.category} | `{_escape(error.url)}` | {_escape(error.message)} |"
            )
        lines.append("")

    lines += ["---", "", "_Generated by endpoint-finder (passive discovery only)._"]
    return "\n".join(lines)


def write(result: ScanResult, path: Path) -> Path:
    """Write the Markdown report.

    Args:
        result: Completed scan result.
        path: Destination file.

    Returns:
        The path that was written.
    """
    path.write_text(build(result), encoding="utf-8")
    return path
